---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets-sealer-env
  namespace: infra
spec:
  encryptedData:
    GH_TOKEN: AgBHogpJjD/7p3AIZbx1lJA2HXLPpCHgUW2U4gd0GVOMMPFQULRYnT+cRmtp1CrLYjXbMFmT9rtYZfhYE62HXassPg1C+1DLUopCVQywE8L9xeTLf19pXmWiMhJgHNAOC40ltFGkqRasGMdwsooadeMp17EC2pcuyHLgC6rbpUWCMLnupELysi1NKXQqC8QtkGD8BONUKEo7tEpo++A+4r3M7M4g+hgQQuIB/vqVS/BBCx9ooT3+GbpcpsC9NFz093J2xF0K7duVNI0PCh1mfXoZwL7N2cwQa5zpwnXORB7yz1+UB5ZTSTzVOR1Am1poz6tmOfHl4fJX6Nck2vo6jww0v03nS1w5nXe3Nr75RVltElemqf69hq6Lk5V7D6z56TQFNMIJ1omYV1pXYtl8iECuMMS1N/t1VudX8O7ZQKu2JUNCH06IXHJkcz5ype3aqUyC7d+VqXYwXQJIEl8Yf65yFENuFKHrF8kAsQ3IRrs/Na5OmkmwKXDMdlqcYFTspizAmqSszevwDn2U0WQif39z0fP9scIbBuocsPJ5UzuDOttYkO03yZtM/225mYiB/iBizziXKvNx1oAJ4LWGswML7C/PilOEsloVJw4Tnh4g4vNX8+aihbRd+7s09DeX7r/kwy0K4E/9bwXjy18rbzSEmKrLzOsouSqIhLXproE3Kji3wZ9mfFFmzS024fFmPJiWpbTGEOW9p+lc5fj65I8AxEHcHB4rbJvc0Bk+a0EtZ1hWQ6RYKsa+
    SEALER_TOKEN: AgAl8/StHmFIVummbxblbXUt5XgGexcaZHwzpnn+rafbhw+1nyN1fsbpOoK6+uwpEUHJOkA39jaorUOKEKKbj7AfPbZBB8m14dNij5WacE8iB+TF5ycwuVgLy4qEYzhzMzO6vOOUl3CzPirSPHCYiVU0GI3n88VT3U6i1zYpDJzdbomZRbZ4mGBg6H23z9VFyLv2HdFCqTTpl+Pe9Lb3PWPSijyYLD5rVcBAEdhkBvxnRxlbE9SPDDQKQRgR/dSU91hsjv5ltFHAJjWiDLRlkJnSSwp/TZtHY5Q9YB+Zjizo9sf/DshJtKcpS9ude4ObjY7+Xt5iYk5F69+TTDyoWw2DX6X1DddZ0CIacNC2At82kfmoFnqrL+5GsXWGHBZY8JgaUO09vDHf6UzIkvalLtFZw9xsXInddNBPxLqXQ97wPjTMr+9RF2dI7VvbsUd+YMwynTHylHAmeVMCeYPH+meEtgnrwnGva/dTmQAn1J0bxpwX/RjAAz3jLat1flmy74bTvgAKAZBUd6qaUIW0xjsWqjTsHNd8KrMk2XLQtnMJnhIHxRBjYCjG13OBr9ZN5fEwU6w/5xSnMeGfW+uDZWxQoEE6RETry59LoyBA+oXhGcweLHqTkmYEIXHSzHR8MRW4ZHgW8YW8LRvhWQ7WskfxkRaISaMif5YZ48yeAsSZNCir+TwcSSuUt2kMfXxQJTxH646uH6Qgp1wYMBdRdbk8dxgTziS8/zB8UioUxq1vXVUjf3OYh3QI0+xDleDdjH0YJPDdOaKLRNxzhORkqC4G
  template:
    metadata:
      creationTimestamp: null
      name: secrets-sealer-env
      namespace: infra
