apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eliseo-data
  namespace: agents
  labels:
    app: eliseo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 10Gi
