apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-spawner
  namespace: agents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
  namespace: agents
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-spawner-binding
  namespace: agents
subjects:
  - kind: ServiceAccount
    name: worker-spawner
    namespace: agents
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
