apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-dispatcher
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: task-dispatcher-qa-scaler
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: task-dispatcher-qa-scaler
subjects:
  - kind: ServiceAccount
    name: task-dispatcher
    namespace: infra
roleRef:
  kind: ClusterRole
  name: task-dispatcher-qa-scaler
  apiGroup: rbac.authorization.k8s.io
