apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ifra-data
  namespace: agents
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 5Gi
