apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - langfuse-secret.yaml
  - neo/
  - mu/
  - beta/
  - flow/
  - ifra-worker/
  - eliseo/
  - neo-worker/
  - beta-worker/
  - worker-template/
  - research-worker/
