apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: task-dispatcher-qa-scaler
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
